### PR TITLE
Create fortnite

### PR DESCRIPTION
**Pull request by wspyams**
This adds a lot to the software and makes it tremendously better.

### CODE REVIEW

**Comment by Richy-Z** [comment]
Good but room for improvement thanks

**Comment by Richy-Z** [comment]
Hi please add copyright notice to comply with legal requirements

**Comment by wspyams** [comment]
i'll get to that right now, thanks for the notice

**Comment by wspyams** [comment]
i've done what i believe is the last piece of the puzzle needed - LGTM!

**Comment by Richy-Z** [comment]
Closed because this issue is now stale. No updates have been added for 30 seconds.

**Comment by wspyams** [comment]
NOOOOOOOOOOOO

**Pull request closed without merging**
